logging:
  level:
    root: INFO
    com.zaxxer.hikari.HikariConfig: DEBUG
    com.zaxxer.hikari: TRACE
server:
  ssl:
    key-alias: tomcat
    key-store-type: PKCS12
    key-store-password: code1995
    key-store: /etc/letsencrypt/live/i5a202.p.ssafy.io/keystore.p12
jasypt:
  encryptor:
    bean: jasyptStringEncryptor
spring:
  jpa:
    hibernate:
      naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
      ddl-auto: update 
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://teamgu-mysql-db.c9wk2jscggn1.ap-northeast-2.rds.amazonaws.com:3306/teamgu?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul&zeroDateTimeBehavior=convertToNull&rewriteBatchedStatements=true
    hikari:
      username: root
      password: teamgupassword
#      idle-timeout: 10000
#      max-lifetime: 420000
#      connection-timeout: 10000
#      validation-timeout: 10000
      maximum-pool-size: 30
      leak-detection-threshold: 2000
  servlet:
    multipart:
      maxFileSize: 30MB
      maxRequestSize: 30MB
  mail:
    host: smtp.gmail.com
    port: 587
    username: ssafy.teamgu@gmail.com
    password: dyrxEw-sysqys-8cotfy
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  redis:
    port: 6379
    host: 127.0.0.1

jwt:
  issuer: teamgu
  secret: h2lsdmVybmluZS10ZWNoLXNwlmauZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQK
  
management:       
  servlet:
    context-path: /manage
  health:
    db:
      enabled: true
    default:
      enabled: true
    diskspace:
      enabled: true