jasypt:
  encryptor:
    bean: jasyptStringEncryptor
spring:
  jpa:
    hibernate:
      naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
      ddl-auto: update 
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver    
    
    url: jdbc:mysql://teamgu-mysql-db.c9wk2jscggn1.ap-northeast-2.rds.amazonaws.com:3306/teamgu?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul&zeroDateTimeBehavior=convertToNull&rewriteBatchedStatements=true
    hikari:
      username: root
      password: teamgupassword
jwt:
  issuer: teamgu
  secret: h2lsdmVybmluZS10ZWNoLXNwlmauZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQK
  
management:       
  servlet:
    context-path: /manage
  health:
    db:
      enabled: true
    default:
      enabled: true
    diskspace:
      enabled: true