name: Deploy storybook to gh-pages

on:
  push:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install dependencies
        run: cd FE && yarn install --prefer-offline --frozen-lockfile

      - name: Build Storybook
        run: cd FE && yarn build-storybook

      # extract branch name
      - name: Get branch name (merge)
        if: github.event_name != 'pull_request'
        shell: bash
        run: echo "BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/} | sed 's/#//')" >> $GITHUB_ENV

      - name: Get branch name (pull request)
        if: github.event_name == 'pull_request'
        shell: bash
        run: echo "BRANCH_NAME=$(echo ${GITHUB_HEAD_REF} | sed 's/#//')" >> $GITHUB_ENV

      - name: Debug
        run: echo ${{ env.BRANCH_NAME }}

      - name: Deploy to Github Pages(pr)
        uses: peaceiris/actions-gh-pages@v3
        if: env.BRANCH_NAME != 'master'
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          publish_dir: ./FE/storybook-static
          keep_files: true
          destination_dir: ${{ env.BRANCH_NAME }}
          commit_message: https://team-gu.github.io/service/${{ env.BRANCH_NAME }}

      - name: Deploy to Github Pages(master)
        uses: peaceiris/actions-gh-pages@v3
        if: env.BRANCH_NAME == 'master'
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          publish_dir: ./FE/storybook-static
          keep_files: true
          commit_message: https://team-gu.github.io/service/
