name: Mirror and run GitLab CI - prj3

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Mirror + trigger CI - prj3
        uses: SvanBoxel/gitlab-mirror-and-ci-action@master
        with:
          args: 'https://lab.ssafy.com/s05-webmobile1-sub3/S05P13A202'
        env:
          GITLAB_HOSTNAME: 'lab.ssafy.com'
          GITLAB_USERNAME: '201704147'
          GITLAB_PASSWORD: ${{ secrets.GITLAB_PASSWORD_PRJ3 }}
          GITLAB_PROJECT_ID: '59048'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
